# Generated by Django 5.1.4 on 2025-03-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='editor_note',
            field=models.TextField(blank=True),
        ),
    ]
